### ISSUE TITLE
Dynamic text saying "Best low tides in daylight in next 30 days are..."

### ISSUE THREAD

**Issue by simonw** [natbat/rockybeaches#17]

**Comment by simonw** [comment]
Find all instances of the lowest-tide-of-the-day that are in daylight hours.

**Comment by simonw** [comment]
```sql
with lowest_tide_per_day as (
  select
    station_id,
    date(datetime) as date,
    time(datetime) as lowest_tide_time,
    min(mllw_feet) as lowest_tide
  from
    tide_predictions
  where
    station_id = 9414131
  group by
    date(datetime)
)
select
  lowest_tide_per_day.*,
  sunrise_sunset.*
from
  lowest_tide_per_day
  join sunrise_sunset on sunrise_sunset.place = 'pillar-point'
  and sunrise_sunset.day = lowest_tide_per_day.date
where
  lowest_tide_per_day.lowest_tide_time > sunrise_sunset.sunrise
  and lowest_tide_per_day.lowest_tide_time < sunrise_sunset.sunset
  and date >= date('now')
order by
  date
```
https://www.rockybeaches.com/data?sql=with+lowest_tide_per_day+as+%28%0D%0A++select%0D%0A++++station_id%2C%0D%0A++++date%28datetime%29+as+date%2C%0D%0A++++time%28datetime%29+as+lowest_tide_time%2C%0D%0A++++min%28mllw_feet%29+as+lowest_tide%0D%0A++from%0D%0A++++tide_predictions%0D%0A++where%0D%0A++++station_id+%3D+9414131%0D%0A++group+by%0D%0A++++date%28datetime%29%0D%0A%29%0D%0Aselect%0D%0A++lowest_tide_per_day.*%2C%0D%0A++sunrise_sunset.*%0D%0Afrom%0D%0A++lowest_tide_per_day%0D%0A++join+sunrise_sunset+on+sunrise_sunset.place+%3D+%27pillar-point%27%0D%0A++and+sunrise_sunset.day+%3D+lowest_tide_per_day.date%0D%0Awhere%0D%0A++lowest_tide_per_day.lowest_tide_time+%3E+sunrise_sunset.sunrise%0D%0A++and+lowest_tide_per_day.lowest_tide_time+%3C+sunrise_sunset.sunset%0D%0A++and+date+%3E%3D+date%28%27now%27%29%0D%0Aorder+by%0D%0A++date

**Comment by simonw** [comment]
Here's what this first version looks like:

<img width="866" alt="Rocky_Beaches__Pillar_Point_Harbor_CA" src="https://user-images.githubusercontent.com/9599/90698461-9b9b1f00-e235-11ea-8eef-60f1726b2f0d.png">

**Comment by natbat** [comment]
Done but needs some styling

**Comment by natbat** [comment]
styling done
