### ISSUE TITLE
Fix width issue on mobile safari

### ISSUE THREAD

**Issue by natbat** [natbat/rockybeaches#25]
![image](https://user-images.githubusercontent.com/72973/90703365-6ea13900-e242-11ea-9868-4a070273a652.png)

**Comment by simonw** [comment]
For some reason disabling `display: grid` on the `.tide-prediction` class fixes the issue (but breaks the display of that component):

![bug](https://user-images.githubusercontent.com/9599/90803371-7eb22a80-e2cd-11ea-90fc-ea20f67e6660.gif)

**Comment by natbat** [comment]
The problem was the minima spans overlapping the right hand side of the box when there was a low tide at midnight.

Before:

<img width="313" alt="Screenshot_8_20_20__12_46_PM" src="https://user-images.githubusercontent.com/72973/90818642-af9d5a00-e2e3-11ea-8f72-7ec6c26f97b9.png">

After:

<img width="145" alt="Screenshot_8_20_20__12_47_PM" src="https://user-images.githubusercontent.com/72973/90818627-a8764c00-e2e3-11ea-8313-aa3b8a3cabf6.png">
