### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by natbat** [natbat/rockybeaches#26]

**Comment by simonw** [comment]
![apple-touch-icon](https://user-images.githubusercontent.com/9599/90834136-60185780-e2fe-11ea-93d6-da9fe94f0101.png)
![favicon-16x16](https://user-images.githubusercontent.com/9599/90834137-60b0ee00-e2fe-11ea-96c4-4aff56398112.png)
![favicon-32x32](https://user-images.githubusercontent.com/9599/90834138-61498480-e2fe-11ea-8466-9169731d8363.png)
