### ISSUE TITLE
Visually distinguish the good vs the rubbish low tides

### ISSUE THREAD

**Issue by simonw** [natbat/rockybeaches#28]
![389859FE-2049-45A9-A716-911D84A738B5](https://user-images.githubusercontent.com/9599/90717170-cbf9b200-e263-11ea-9921-fc45b98bb7d2.jpeg)

They all are represented by the same colour red lines. But some of these low tides are good for tide pooling  and others are rubbish.

Could visually distinguish the lowest rise of the day - or could use a different colour for tides that are below 0.

**Comment by natbat** [comment]
the styling was this is ticket the backend is #29
