### ISSUE TITLE
tide depth view should be for the LOWEST tide IN DAYLIGHT

### ISSUE THREAD

**Issue by natbat** [natbat/rockybeaches#30]
The site makes the assumption that you only want to go tidepooling in daylight (if you are advanced enough to do night tidepooling you can look at other tide times apps

**Comment by simonw** [comment]
That's this component here - it should be showing lowest daylight tide, not lowest tide overall:

<img width="210" alt="Rocky_Beaches__Pillar_Point_Harbor_CA" src="https://user-images.githubusercontent.com/9599/90824539-6c93b480-e2ec-11ea-8c2e-03d9e0e4217b.png">
