### ISSUE TITLE
Data for the tide prediction text should match the lowest tide time in daylight

### ISSUE THREAD

**Issue by natbat** [natbat/rockybeaches#32]
this needs to be true:

The lowest tide in daylight today is -0.56ft at 06:18

At the moment its showing the lowest tide info not the lowest tide in daylight

**Comment by simonw** [comment]
<img width="785" alt="Rocky_Beaches__Pillar_Point_Harbor_CA" src="https://user-images.githubusercontent.com/9599/90824621-87febf80-e2ec-11ea-8cdd-d897ec08314b.png">
