### ISSUE TITLE
Next 4 low tides showing incorrect details

### ISSUE THREAD

**Issue by natbat** [natbat/rockybeaches#65]
![image](https://user-images.githubusercontent.com/72973/91907386-a2c32380-ec5e-11ea-9a4e-aa6fc63ea019.png)

![image](https://user-images.githubusercontent.com/72973/91907423-b1113f80-ec5e-11ea-985e-ff72449c3746.png)

**Comment by simonw** [comment]
I'm pretty sure this means there's an error in this SQL statement from #55:

https://github.com/natbat/rockybeaches/blob/683f95b01f37c61c77275380f6abd51c599e263f/plugins/template_vars.py#L55-L112

**Comment by simonw** [comment]
Compare https://www.rockybeaches.com/data?sql=with+daylight_tides+as+%28%0D%0A++select%0D%0A++++tide_predictions.datetime%2C%0D%0A++++time%28tide_predictions.datetime%29%2C%0D%0A++++tide_predictions.mllw_feet%2C%0D%0A++++sunrise_sunset.sunrise%2C%0D%0A++++sunrise_sunset.sunset%0D%0A++from%0D%0A++++tide_predictions%0D%0A++++join+sunrise_sunset+on+sunrise_sunset.place+%3D+%3Aplace_slug%0D%0A++++and+sunrise_sunset.day+%3D+date%28tide_predictions.datetime%29%0D%0A++where%0D%0A++++time%28tide_predictions.datetime%29+%3E%3D+sunrise%0D%0A++++and+time%28tide_predictions.datetime%29+%3C%3D+sunset%0D%0A++++and+tide_predictions.station_id+%3D+%28%0D%0A++++++select%0D%0A++++++++station_id%0D%0A++++++from%0D%0A++++++++places%0D%0A++++++where%0D%0A++++++++slug+%3D+%3Aplace_slug%0D%0A++++%29%0D%0A%29%2C%0D%0Alowest_daylight_tide_per_day+as+%28%0D%0A++select%0D%0A++++date%28datetime%29+as+date%2C%0D%0A++++min%28mllw_feet%29+as+lowest_daylight_tide%2C%0D%0A++++time%28datetime%29+as+time%2C%0D%0A++++sunrise%2C%0D%0A++++sunset%0D%0A++from%0D%0A++++daylight_tides%0D%0A++group+by%0D%0A++++date%28datetime%29%0D%0A++having%0D%0A++++mllw_feet+%3D+min%28mllw_feet%29%0D%0A%29%0D%0Aselect%0D%0A++*%0D%0Afrom%0D%0A++lowest_daylight_tide_per_day&place_slug=fiscalini-ranch to the days listed on https://www.rockybeaches.com/us/fiscalini-ranch#when-to-visit

**Comment by simonw** [comment]
We checked that our big tide time charts for Fiscalini Ranch match the charts on the NOAA page and they do, so those look to be correct.

https://tidesandcurrents.noaa.gov/noaatidepredictions.html?id=9412110&units=standard&bdate=20200903&edate=20200904&timezone=LST/LDT&clock=12hour&datum=MLLW&interval=hilo&action=dailychart

<img width="1592" alt="Tide_Predictions_-_NOAA_Tides___Currents_and_Rocky_Beaches__Fiscalini_Ranch" src="https://user-images.githubusercontent.com/9599/91928861-f438d600-ec91-11ea-973f-d55c9aade96a.png">

**Comment by simonw** [comment]
I figured out what's going on here. The problem is that the area at the top has logic based on when the lowest tide during daylight is - which means that even if the tides lowest exact point is at night it will still detect the slightly-less-low point at day-break.

The graphs further down the page use peak detection to figure out which are the two (or more) lowest tide points of the day, and then figures out which of those are during daylight.

Hence the difference in what data is displayed.

The fix is that the four suggestions at the top should NOT be powered by their own SQL query. They should instead be derived from code that looks at the 30 charts shown lower down the page.

**Comment by simonw** [comment]
I spotted a day with no lowest-tide in daylight at all: September 20th 2020 at Fiscalini Ranch. Thankfully our code handles that just fine:

<img width="766" alt="Rocky_Beaches__Fiscalini_Ranch" src="https://user-images.githubusercontent.com/9599/91930699-67444b80-ec96-11ea-9795-343435e415b2.png">
